### PR TITLE
Npm package wasm

### LINKED ISSUE #3: npm package js version?
hi, this project is very cool! thanks for all the work.

Are you planning to publish the js version as an npm package?
I'd be happy to help craft something if you don't have the time.

Cheers

### PR DESCRIPTION
**Pull request by radames**
Couple of comments: 

The package is live here https://www.npmjs.com/package/skeleton-tracing-wasm

I've changed the `compile.sh` so `emcc` bundle the WASM file inside the js wrapper as a base64 string. This is much easier to import in different environments, and the WASM and js together is about 35kb.
I've removed the `wrapper.js` and replace it with a slightly different approach to load the WASM.

Everything is on `index.js`

there is a class with a static method to load the WASM module 

```js

class TraceSkeleton {
  constructor(tracer) {
    if (typeof tracer === 'undefined') {
      throw new Error('Cannot be called directly');
    }
    this.tracer = tracer;
  }
  static load() {
    return _TRACESKELETON().then((d) => {
      return new TraceSkeleton(d);
    });
  }
...

```
Your api has changed a little, for example of p5.js you will need an async function to load the WASM first

```js

var tracer;

async function setup() {
   tracer = await TraceSkeleton.load(); // Load WASM Tracer
}
```

then the rest is following your original api

Or instead of async/await you can do

```js

TraceSkeleton.load().then(tracer => {
	// wasm module loaded
	// here is your code 
	const { polylines,rects } = tracer.fromCanvas(HTMLCANVAS)

})

```

Here is on example on Observable
https://observablehq.com/d/be83f67f3de2ea89

And I've also update your index.html example!

this will close #3 !!

ps. it's been fun to play with emscripten!

### CODE REVIEW

**Comment by LingDong-** [comment]
Great, thanks a lot!
Pretty cool that you managed to get rid of the extra .wasm file and embed it in JS. The observable demo looks nice too.

P.S. I'm recently teaching myself to write [wasm by hand](https://github.com/LingDong-/wasm-fun), which as the benefit of producing really optimized file sizes. The skeleton-tracing algorithm might be too complex to manually port to webassembly, but if I ever mange to do it maybe I'll update this package :)

**Comment by radames** [comment]
That's so cool! Thanks for the great examples! With the WAT language it looks much more digestible, I'll try later!

**Comment by LingDong-** [comment]
Hi @radames , seems like I've been successful with implementing the algorithm with handwritten WebAssembly :)

https://github.com/LingDong-/skeleton-tracing/blob/master/wat/traceskeleton.wat

My initial tests show that it's about 5x faster than vanilla JS, and 3x faster than wasm compiled by emscripten (and 10x smaller in file size!)

**Comment by radames** [comment]
hi @LingDong- that's awesome!! Considering the performance improvements, I should use your new wasm on the npm packaged. The api seems a bit different right?

**Comment by LingDong-** [comment]
Hi @radames,

Thanks! Yes the API is a bit different, but I think it's better since it's reading off the internal datastructure directly (the emscripten version is encoding output to a string which is then parsed from javascript.)

However, it seems that on node.js, this version runs even slower than vanilla javascript. In a browser (Chrome 84, macOS 10.14), it is much faster than JS. (Seems like the speed of the wasm in the two environments is very similar, but node JS is much faster than browser JS.)

I haven't tested the emscripten version on node.js yet...

**Comment by radames** [comment]
That's pretty impressive! Also  weird the differences between node and chrome, aren't they using the same v8 engine? 
I'll look into convert the wasm npm package to your new code. Thanks!

**Pull request merged**
